repos:
  - repo: "https://github.com/pycqa/isort"
    rev: 5.8.0
    hooks:
      - id: isort
        args:
          - "--profile"
          - black
        name: isort
  - repo: "https://github.com/ambv/black"
    rev: 21.5b0
    hooks:
      - id: black
        language_version: python3
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v0.812
    hooks:
      - id: mypy
